//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCheckPoint.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingMaterialValue
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Count { get; set; }
        public string NumberDocument { get; set; }
        public Nullable<int> IDAutoTransport { get; set; }
    
        public virtual AutoTransport AutoTransport { get; set; }
    }
}
