//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCheckPoint.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTransport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutoTransport()
        {
            this.AccountingMaterialValue = new HashSet<AccountingMaterialValue>();
        }
    
        public int ID { get; set; }
        public string Mark { get; set; }
        public string StateNumber { get; set; }
        public string SeriesNumber { get; set; }
        public string Color { get; set; }
        public Nullable<int> IDPass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingMaterialValue> AccountingMaterialValue { get; set; }
        public virtual Pass Pass { get; set; }
    }
}
