//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCheckPoint.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTransport
    {
        public int ID { get; set; }
        public string Mark { get; set; }
        public string StateNumber { get; set; }
        public string SeriesNumber { get; set; }
        public string Color { get; set; }
        public Nullable<int> IDPass { get; set; }
    
        public virtual Pass Pass { get; set; }
    }
}
