//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCheckPoint.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoArrivalDeparture
    {
        public int ID { get; set; }
        public Nullable<int> IDEmployee { get; set; }
        public Nullable<int> IDExternalPerson { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public Nullable<System.TimeSpan> TotalTime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExternalPerson ExternalPerson { get; set; }
    }
}
