//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemCheckPoint.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pass()
        {
            this.AccountingMaterialValue = new HashSet<AccountingMaterialValue>();
            this.AutoTransport = new HashSet<AutoTransport>();
            this.Employee = new HashSet<Employee>();
            this.ExternalPerson = new HashSet<ExternalPerson>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDTypePass { get; set; }
        public Nullable<System.DateTime> DateOfFormation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountingMaterialValue> AccountingMaterialValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoTransport> AutoTransport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalPerson> ExternalPerson { get; set; }
        public virtual TypePass TypePass { get; set; }
    }
}
